print("Below listed are 6th semester courses")

print("DevOps Practices - 3 credits")
print("Software Project Management - 3 credits")
print("High Performance Computing - 4 credits")
print("Environment and Sustainability - 3 credits")
print("Career Skills for IT Companies - 3 credits")
print("Marketing Strategies and Planning - 3 credits")
print("Undergraduate Research - 1 credit")
print("Seminar - 1 credit")